In [2]:
import numpy as np
import pandas as pd

df = pd.read_csv('C:\\Users\\piyush.c\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Desktop\\Task1\\shop_status_details_01-01-2018 to 31-12-2018.csv')

In [3]:
df.head(10)

,distCode,distName,officeCode,officeName,shopNo,month,year,noOfRcs,noOfTrans,riceAfsc,riceFsc,riceAap,wheat,sugar,rgdal,kerosene,totalAmount,salt,otherShopTransCnt
0,532,Adilabad,532001,Talamadugu,1901001,4,2018,882,884,1260,17472,0,0,0,0,0,18732.0,0,27
1,532,Adilabad,532001,Talamadugu,1901002,4,2018,538,538,595,10794,0,0,0,0,0,11389.0,0,6
2,532,Adilabad,532001,Talamadugu,1901003,4,2018,260,260,595,5200,0,0,0,0,0,5795.0,0,3
3,532,Adilabad,532001,Talamadugu,1901004,4,2018,350,352,490,7326,10,0,13,0,0,7991.5,0,5
4,532,Adilabad,532001,Talamadugu,1901005,4,2018,866,873,4795,16560,0,0,137,0,0,23204.5,0,7
5,532,Adilabad,532001,Talamadugu,1901006,4,2018,411,411,1120,8064,0,0,0,0,0,9184.0,0,2
6,532,Adilabad,532001,Talamadugu,1901007,4,2018,472,472,350,9354,0,0,6,0,0,9785.0,0,10
7,532,Adilabad,532001,Talamadugu,1901008,4,2018,387,387,2625,6672,0,0,0,0,0,9297.0,0,55
8,532,Adilabad,532001,Talamadugu,1901009,4,2018,298,307,665,6768,0,0,0,0,0,7433.0,0,2
9,532,Adilabad,532001,Talamadugu,1901010,4,2018,825,825,3291,16038,0,0,89,0,0,20530.5,0,12

In [4]:
df.shape

(179393, 19)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 179393 entries, 0 to 179392
Data columns (total 19 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   distCode           179393 non-null  int64
 1   distName           179393 non-null  str
 2   officeCode         179393 non-null  int64
 3   officeName         179393 non-null  str
 4   shopNo             179393 non-null  int64
 5   month              179393 non-null  int64
 6   year               179393 non-null  int64
 7   noOfRcs            179393 non-null  int64
 8   noOfTrans          179393 non-null  int64
 9   riceAfsc           179393 non-null  int64
 10  riceFsc            179393 non-null  int64
 11  riceAap            179393 non-null  int64
 12  wheat              179393 non-null  int64
 13  sugar              179393 non-null  int64
 14  rgdal              179393 non-null  int64
 15  kerosene           179393 non-null  int64
 16  totalAmount        179393 non-null  float64
 17  salt               179393 non-null  int64
 18  otherShopTransCnt  179393 non-null  int64
dtypes: float64(1), int64(16), str(2)
memory usage: 26.0 MB

In [6]:
df.isnull().sum()

distCode             0
distName             0
officeCode           0
officeName           0
shopNo               0
month                0
year                 0
noOfRcs              0
noOfTrans            0
riceAfsc             0
riceFsc              0
riceAap              0
wheat                0
sugar                0
rgdal                0
kerosene             0
totalAmount          0
salt                 0
otherShopTransCnt    0
dtype: int64

In [7]:
# shop == 0 and no of trsn > 0 
anamoly = df[(df['noOfRcs'] == 0)& (df['noOfTrans'] > 0)].count()
print(anamoly.shape[0])
anamoly.head()
anamoly.isnull().sum()

19

np.int64(0)

In [8]:
df['totalAmount'] = df['totalAmount'].abs()

In [9]:
df['is_overflow'] = df['noOfTrans']>df['noOfRcs']

In [10]:
df['total_rice'] = df['riceAfsc'] + df['riceFsc'] + df['riceAap']

In [11]:
df['total_rice']

0         18732
1         11389
2          5795
3          7826
4         21355
          ...
179388     6274
179389     2195
179390     3802
179391     4079
179392     2458
Name: total_rice, Length: 179393, dtype: int64

In [12]:
# total_rice, wheat, sugar, rgdal,  kerosene, and salt
df['total_volume'] = df['total_rice'] + df['wheat'] +df['sugar'] +df['rgdal'] +df['kerosene'] + df['salt']

In [13]:
df['trans_rate'] = np.where(df['noOfRcs'] == 0,0,(df['noOfTrans'] / df['noOfRcs']) * 100)

In [14]:
df['trans_rate'].sample(5)

50076     100.518135
137948    100.234742
145590    100.543478
136020    100.000000
130125    100.235294
Name: trans_rate, dtype: float64

In [15]:
def total(totalAmount):
    if totalAmount > 15000:
        return 'High Performer'
    elif totalAmount < 5000 and totalAmount > 15000:
        return 'Average Performent'
    else:
        return 'Low Performer'
df['shop_category'] = df['totalAmount'].map(total)

In [16]:
district_summary = df.groupby('distName').agg({
    'totalAmount' : 'sum',
    'noOfTrans' : 'mean',
    'total_volume': 'sum'
})

In [17]:
top_districts = district_summary.sort_values(
    by='totalAmount',
    ascending=False
).head(5)

print(top_districts)

             totalAmount   noOfTrans  total_volume
distName
Hyderabad    262918493.5  718.407276     122426616
Medchal      157213593.0  611.558615      85678982
Ranga Reddy  134212344.5  463.284205      96180568
Mahbubnagar   78246453.0  361.297603      76362650
Sangareddy    77980233.0  375.353631      77706967

In [18]:
df = df.drop(columns=['riceAfsc','riceFsc','riceAap'])

In [19]:
df.describe()

,distCode,officeCode,shopNo,month,year,noOfRcs,noOfTrans,wheat,sugar,rgdal,kerosene,totalAmount,salt,otherShopTransCnt,total_rice,total_volume,trans_rate
count,179393.000000,179393.000000,1.793930e+05,179393.000000,179393.0,179393.000000,179393.000000,179393.000000,179393.000000,179393.0,179393.000000,179393.000000,179393.000000,179393.000000,179393.000000,179393.000000,179393.000000
mean,779.748747,779772.610381,2.849639e+06,6.491797,2018.0,411.103560,415.781591,57.029449,12.715485,0.0,40.880430,10381.486410,0.459433,56.357807,8724.637032,8835.721829,101.036232
std,191.990685,191975.275407,9.090833e+05,3.541045,0.0,205.952734,213.185199,252.031267,20.147479,0.0,161.548386,9279.115102,11.930240,118.181797,4610.025649,4837.291413,10.134033
min,532.000000,532001.000000,1.403001e+06,1.000000,2018.0,1.000000,1.000000,0.000000,0.000000,0.0,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,100.000000
25%,538.000000,538032.000000,2.049115e+06,3.000000,2018.0,277.000000,279.000000,0.000000,0.000000,0.0,0.000000,5989.000000,0.000000,1.000000,5806.000000,5834.000000,100.000000
50%,925.000000,925012.000000,2.812009e+06,6.000000,2018.0,382.000000,385.000000,0.000000,1.000000,0.0,0.000000,8259.500000,0.000000,8.000000,7980.000000,8013.000000,100.000000
75%,934.000000,934009.000000,3.709010e+06,10.000000,2018.0,505.000000,509.000000,0.000000,21.000000,0.0,0.000000,11193.000000,0.000000,51.000000,10635.000000,10709.000000,100.542005
max,941.000000,941017.000000,4.417020e+06,12.000000,2018.0,3914.000000,3972.000000,5322.000000,276.000000,0.0,3388.000000,183733.000000,1027.000000,1768.000000,83196.000000,86754.000000,2400.000000

In [20]:
df = df.to_csv('engineered_shop_data.csv',index='False')